ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

nodes = [
  { :hostname=> 'worker01', :ip=> '10.11.10.2', :memory=> 2048, :cpu=> 1, :boxname=> 'ubuntu/focal64', :port=> 2222 },
  { :hostname=> 'worker02', :ip=> '10.11.10.3', :memory=> 2048, :cpu=> 1, :boxname=> 'ubuntu/focal64', :port=> 2223 },
  { :hostname=> 'manager01', :ip=> '10.11.10.1', :memory=> 2048, :cpu=> 1, :boxname=> 'ubuntu/focal64', :port=> 2221 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:boxname]
      nodeconfig.vm.network "forwarded_port", id: "ssh", guest: 22, host: node[:port]
      nodeconfig.vm.network "private_network", ip: node[:ip], virtualbox__intnet: true
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.provision "file", source: "./scripts/#{node[:hostname]}.sh", destination: "~/#{node[:hostname]}.sh"
      if node[:hostname] == 'manager01'
        nodeconfig.vm.provision "file", source: "./docker-compose.yml", destination: "~/docker-compose.yml"
      end

      nodeconfig.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("#{ENV['USERPROFILE']}/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          chmod +x /home/vagrant/#{node[:hostname]}.sh
          sed -i -e 's/\r$//' /home/vagrant/#{node[:hostname]}.sh
          ./#{node[:hostname]}.sh
          SHELL
      end

      nodeconfig.vm.provider "virtualbox" do |vb|
          vb.name = node[:hostname]
          vb.memory = node[:memory]
          vb.cpus = node[:cpu]
      end
    end
  end
end